services:
  openbabywisher:
    build: .
    container_name: openbabywisher
    # Override with your host user's UID:GID (run: id -u && id -g)
    # This ensures the container can write to ./data and ./uploads
    user: "1001:1001"
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - API_TOKEN=${API_TOKEN:-your-admin-token-change-this}
      - BABY_NAME=${BABY_NAME:-our little one}
      - DATABASE_URL=sqlite:////app/data/wishlist.db
      - PORT=5000
      - NOTIFICATION_URL=${NOTIFICATION_URL:-}
    volumes:
      - ./data:/app/data:rw
      - ./uploads:/app/uploads:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

